### ISSUE TITLE
"Invalid TimeOfDay format" when no default value set

### ISSUE THREAD

**Issue by RedAvenge** [neohelden/Flutter-AdaptiveCards#18]
Greetings,
when a card is parsed with an Input.Time field which as no `vaule` field set, the framework runs into an assertion fail with the message `Invalid TimeOfDay format`.

This is because if no `vaule` is set, an empty string is set by the framework as the default value and in the `parseTime` method of the time widget there is only a check if the given time string is not null but not if the string is empty.
I hope the image down below helps to understand: The `adaptiveMap` does not contain the `value` field. In the `parseTime` method the given string is empty and because there is only a null check in line 225, the assertion in line 227 fails.

The fix is probably to add/edit a "is not empty" check to the if case in line 225.

![AdaptiveCardsFlutter-Bug](https://user-images.githubusercontent.com/45849422/77889364-01c6db80-726e-11ea-85b2-7a7b9153cb8b.JPG)
File of the image: `lib/src/elements/input.dart`

**Comment by Norbert515** [comment]
Thank you for the detailed report, fixed it and bumped the version to 0.0.3

**Comment by RedAvenge** [comment]
I thank you for the quick response.
One thing I have noticed: If I dont set a the `value` field in the card, the framework sets the current time as the default value. So far so good. But in my case it would be better if the given `placeholder` value were displayed just like with the `Input.Date` fields.

Looking in the code I think the different behaviours comes from the `initState` methods (line 163 and 215). In the date widget when no `value` is set, the `DateTime.parse` will fail and "assign" `null` but in the time widget the current time is assigned and therefor the placeholder value is ignored.

In my opinion both cases are good to have. Maybe the priority could be first use the given `value`, if not set use the `placeholder` and if that is also not set use the current time or date. This should be then consistent along both, date and time, widgets.
