### ISSUE TITLE
verticalContentAlignment and horizontalAlignment don't work in ColumnSet

### ISSUE THREAD

**Issue by Curvel** [neohelden/Flutter-AdaptiveCards#24]
Even when using **"verticalContentAlignment": "Center"** in a ColumnSet, the alignment is **top**, instead of **center**

**Comment by Curvel** [comment]
And **horizontalAlignment** is always **left**

**Comment by beevelop** [comment]
Currently affected by https://github.com/flutter/flutter_markdown/issues/171

**Comment by Curvel** [comment]
The Designer https://adaptivecards.io/designer/ doesn't have support for vertical alignment in columnSets. Therefore, only horizontal alignment will be implemented
