### ISSUE TITLE
"width" and "height" doen't work on images in a column with stretch

### ISSUE THREAD

**Issue by Curvel** [neohelden/Flutter-AdaptiveCards#25]
When using:

` {
"type": "Image",
 "url": "yourUrl",
"width": "50px",
 "horizontalAlignment": "Center",
 "height": "50px"
},`

inside a column with the **stretch** attribute the **width** and **height** are ignored and the stretched column width is used.

**Comment by Curvel** [comment]
Fixed with: https://github.com/neohelden/Flutter-AdaptiveCards/pull/30

**Comment by beevelop** [comment]
MR has been merged
